install: true # we don't need any special installation
script: make test
branches:
    only:
        - master

matrix:
    include:
        - language: python
          python: "3.5"
        - language: python
          python: "3.6"
        - language: python
          python: "3.7"
          dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
