language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install: true # we don't need any special installation
script: make test
branches:
    only:
        - master
